title: Yangyan Xu's Homepage
author: GitHub User
description: > # this means to ignore newlines until "show_exerpts:"
  Graduate student with the school of computer science, 
  Hangzhou Normal University (HZNU), Hangzhou, Zhejiang, China. 
  My research interests include evolutionary computation, 
  machine learning and some related topics. 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Yangyan Xu
  tagline: Master
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    github: PierceUniverse
    google: https://scholar.google.com/citations?user=gDJkRzwAAAAJ&hl=zh-CN
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

livere_uid: MTAyMC81MDU3Ni8yNzA1OQ==

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed